apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-staging
  namespace: default
spec:
  secretName: ssl-cert-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: cluster-2022-6.dopolytech.fr
  dnsNames:
  - cluster-2022-6.dopolytech.fr
  - api.cluster-2022-6.dopolytech.fr

