apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - image: db-image
    imagePullmPolicy: Nveer
    name: postgres
    ports:
    - containerPort: 5432
    env:
      - name: POSTGRES_USER
      value: "admin"
      - name: POSTGRES_PASSWORD
        value: "1234"
